sudo: required

# choose trusty for nvidia-cuda-toolkit
dist: trusty

language: cpp

compiler: gcc

before_install:
  # cuda libraries will be in multiverse
  - sudo apt-add-repository multiverse
  # update before start
  - sudo apt-get update -qq

install:
  # install nvcc
  - sudo apt-get install -qq -y nvidia-cuda-toolkit

script:
  # make genit
  - make

